name: moely_app
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  permission_handler: ^11.0.0
flutter:
  uses-material-design: true
